Repository globus/globus-automate-client, pull requests merged in 2021-12, with the labels that each got.

#108 Fix a KeyError crash that occurs when `-v` is passed
  changelog.d/20211202_152823_kurtmckee_fix_key_error_sc_12117.rst
  globus_automate_client/cli/helpers.py
Labels: bug

#109 Allows workflow to be reused
  .github/workflows/has_changelog.yaml
Labels: no-news-is-good-news

#114 Fix a ValueError crash when displaying a flow
  changelog.d/20211209_145022_kurtmckee_fix_flow_display_crash_sc_12186.rst
  globus_automate_client/cli/flows.py
  globus_automate_client/cli/rich_helpers.py
Labels: bug

#107 Adds WORKFLOW.md file
  WORKFLOW.md
Labels: no-news-is-good-news

#118 Add `notify_on_*` options to the transfer example JSON file
  changelog.d/20211214_142801_kurtmckee_doc_notify_opts_sc_11450.rst
  docs/source/globus_action_providers.rst
  examples/action_bodies/transfer.json
Labels: documentation

#117 Expand testing
  .pre-commit-config.yaml
  Makefile
  examples/notebooks/flow-deploy-and-monitor.ipynb
  examples/notebooks/flow_discovery.ipynb
  globus_automate_client/cli/auth.py
  globus_automate_client/cli/helpers.py
  globus_automate_client/flows_client.py
  poetry.lock
  pyproject.toml
  tests/test_helpers.py
  tox.ini
Labels: no-news-is-good-news
